# Generated by Django 2.2.17 on 2021-03-24 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_countrycodes_iso_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='sent_at',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
