# Generated by Django 2.2.17 on 2021-03-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_otp_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='sent_at',
        ),
    ]
