# Generated by Django 2.2.17 on 2021-04-10 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210325_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('backgroung_img', models.ImageField(default='default.jpg', upload_to='background_pics')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('url', models.CharField(max_length=100, null=True)),
                ('dob', models.DateField(null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
